-- FBMS initial schema (PostgreSQL). Mirrors ../001_init.sql (SQLite).
-- Money columns are INTEGER cents; timestamps are ISO-8601 TEXT, as in SQLite.

CREATE TABLE settings (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      TEXT NOT NULL,
  full_name     TEXT NOT NULL,
  role          TEXT NOT NULL CHECK (role IN ('admin','manager','cashier','kitchen')),
  password_hash TEXT NOT NULL,
  pin_hash      TEXT,
  active        INTEGER NOT NULL DEFAULT 1,
  created_at    TEXT NOT NULL
);

-- Usernames are case-insensitive (SQLite: COLLATE NOCASE).
CREATE UNIQUE INDEX idx_users_username ON users (lower(username));

CREATE TABLE sessions (
  token_hash TEXT PRIMARY KEY,
  user_id    INTEGER NOT NULL REFERENCES users(id),
  terminal   TEXT,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL
);
CREATE INDEX idx_sessions_user ON sessions(user_id);

CREATE TABLE categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name   TEXT NOT NULL,
  icon   TEXT NOT NULL DEFAULT '🍽️',
  color  TEXT NOT NULL DEFAULT '#e11d48',
  sort   INTEGER NOT NULL DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id INTEGER NOT NULL REFERENCES categories(id),
  sku         TEXT UNIQUE,
  name        TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  price       INTEGER NOT NULL CHECK (price >= 0),
  icon        TEXT NOT NULL DEFAULT '🍽️',
  station     TEXT NOT NULL DEFAULT 'kitchen',
  sort        INTEGER NOT NULL DEFAULT 0,
  active      INTEGER NOT NULL DEFAULT 1,
  available   INTEGER NOT NULL DEFAULT 1,
  vat_exempt_eligible INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX idx_items_category ON items(category_id);

CREATE TABLE modifier_groups (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL,
  min_select INTEGER NOT NULL DEFAULT 0,
  max_select INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE modifier_options (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id    INTEGER NOT NULL REFERENCES modifier_groups(id),
  name        TEXT NOT NULL,
  price_delta INTEGER NOT NULL DEFAULT 0,
  is_default  INTEGER NOT NULL DEFAULT 0,
  sort        INTEGER NOT NULL DEFAULT 0,
  active      INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX idx_modopt_group ON modifier_options(group_id);

CREATE TABLE item_modifier_groups (
  item_id  INTEGER NOT NULL REFERENCES items(id),
  group_id INTEGER NOT NULL REFERENCES modifier_groups(id),
  sort     INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (item_id, group_id)
);

CREATE TABLE ingredients (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL UNIQUE,
  unit          TEXT NOT NULL,
  stock         DOUBLE PRECISION NOT NULL DEFAULT 0,
  reorder_level DOUBLE PRECISION NOT NULL DEFAULT 0,
  cost_per_unit INTEGER NOT NULL DEFAULT 0
);

-- Bill of materials: how much of each ingredient one unit of an item consumes.
CREATE TABLE recipes (
  item_id       INTEGER NOT NULL REFERENCES items(id),
  ingredient_id INTEGER NOT NULL REFERENCES ingredients(id),
  qty           DOUBLE PRECISION NOT NULL,
  PRIMARY KEY (item_id, ingredient_id)
);

-- Modifier options (e.g. "Coke Large", "Add Cheese") can consume stock too.
CREATE TABLE option_recipes (
  option_id     INTEGER NOT NULL REFERENCES modifier_options(id),
  ingredient_id INTEGER NOT NULL REFERENCES ingredients(id),
  qty           DOUBLE PRECISION NOT NULL,
  PRIMARY KEY (option_id, ingredient_id)
);

CREATE TABLE stock_movements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ingredient_id INTEGER NOT NULL REFERENCES ingredients(id),
  qty_change    DOUBLE PRECISION NOT NULL,
  reason        TEXT NOT NULL CHECK (reason IN ('sale','receive','waste','adjust','refund')),
  ref           TEXT,
  user_id       INTEGER REFERENCES users(id),
  created_at    TEXT NOT NULL
);
CREATE INDEX idx_stockmov_ing ON stock_movements(ingredient_id, created_at);

CREATE TABLE dining_tables (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name   TEXT NOT NULL UNIQUE,
  seats  INTEGER NOT NULL DEFAULT 4,
  area   TEXT NOT NULL DEFAULT 'Main',
  active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE shifts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         INTEGER NOT NULL REFERENCES users(id),
  terminal        TEXT NOT NULL,
  status          TEXT NOT NULL CHECK (status IN ('open','closed')),
  opening_float   INTEGER NOT NULL,
  expected_cash   INTEGER,
  counted_cash    INTEGER,
  variance        INTEGER,
  opened_at       TEXT NOT NULL,
  closed_at       TEXT,
  notes           TEXT
);
CREATE INDEX idx_shifts_user_status ON shifts(user_id, status);

CREATE TABLE cash_movements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shift_id   INTEGER NOT NULL REFERENCES shifts(id),
  type       TEXT NOT NULL CHECK (type IN ('pay_in','payout','drop')),
  amount     INTEGER NOT NULL CHECK (amount > 0),
  reason     TEXT NOT NULL,
  user_id    INTEGER NOT NULL REFERENCES users(id),
  created_at TEXT NOT NULL
);

CREATE TABLE orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no           INTEGER NOT NULL,
  business_date      TEXT NOT NULL,
  type               TEXT NOT NULL CHECK (type IN ('dine_in','take_out','drive_thru','delivery')),
  source             TEXT NOT NULL DEFAULT 'pos' CHECK (source IN ('pos','kiosk')),
  status             TEXT NOT NULL CHECK (status IN ('open','paid','voided','refunded')),
  kitchen_status     TEXT CHECK (kitchen_status IN ('queued','preparing','ready','served')),
  table_id           INTEGER REFERENCES dining_tables(id),
  customer_name      TEXT,
  notes              TEXT,
  guest_count        INTEGER NOT NULL DEFAULT 1,
  sc_pwd_count       INTEGER NOT NULL DEFAULT 0,
  sc_pwd_ids         TEXT,
  discount_label     TEXT,
  discount_type      TEXT CHECK (discount_type IN ('percent','amount')),
  discount_value     INTEGER NOT NULL DEFAULT 0,
  discount_approved_by INTEGER REFERENCES users(id),
  service_charge_rate INTEGER NOT NULL DEFAULT 0, -- basis points
  subtotal           INTEGER NOT NULL DEFAULT 0,
  sc_pwd_discount    INTEGER NOT NULL DEFAULT 0,
  other_discount     INTEGER NOT NULL DEFAULT 0,
  vatable_sales      INTEGER NOT NULL DEFAULT 0,
  vat_amount         INTEGER NOT NULL DEFAULT 0,
  vat_exempt_sales   INTEGER NOT NULL DEFAULT 0,
  service_charge     INTEGER NOT NULL DEFAULT 0,
  total              INTEGER NOT NULL DEFAULT 0,
  or_number          INTEGER UNIQUE,
  created_by         INTEGER REFERENCES users(id),
  cashier_id         INTEGER REFERENCES users(id),
  shift_id           INTEGER REFERENCES shifts(id),
  stock_deducted     INTEGER NOT NULL DEFAULT 0,
  void_reason        TEXT,
  voided_by          INTEGER REFERENCES users(id),
  created_at         TEXT NOT NULL,
  updated_at         TEXT NOT NULL,
  sent_at            TEXT,
  ready_at           TEXT,
  served_at          TEXT,
  paid_at            TEXT,
  UNIQUE (business_date, order_no)
);
CREATE INDEX idx_orders_status ON orders(status, business_date);
CREATE INDEX idx_orders_kitchen ON orders(kitchen_status);
CREATE INDEX idx_orders_paid ON orders(paid_at);

CREATE TABLE order_lines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id    INTEGER NOT NULL REFERENCES orders(id),
  item_id     INTEGER NOT NULL REFERENCES items(id),
  name        TEXT NOT NULL,
  station     TEXT NOT NULL,
  base_price  INTEGER NOT NULL,
  unit_price  INTEGER NOT NULL,
  qty         INTEGER NOT NULL CHECK (qty > 0),
  line_total  INTEGER NOT NULL,
  modifiers   TEXT NOT NULL DEFAULT '[]', -- JSON [{option_id, group, name, price_delta}]
  notes       TEXT,
  sent        INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT NOT NULL
);
CREATE INDEX idx_lines_order ON order_lines(order_id);

CREATE TABLE payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id     INTEGER NOT NULL REFERENCES orders(id),
  method       TEXT NOT NULL CHECK (method IN ('cash','card','gcash','maya','voucher')),
  amount       INTEGER NOT NULL,       -- amount applied to the bill
  tendered     INTEGER NOT NULL,       -- amount handed over (cash may exceed amount)
  change_given INTEGER NOT NULL DEFAULT 0,
  reference    TEXT,
  shift_id     INTEGER REFERENCES shifts(id),
  user_id      INTEGER REFERENCES users(id),
  created_at   TEXT NOT NULL
);
CREATE INDEX idx_payments_order ON payments(order_id);
CREATE INDEX idx_payments_shift ON payments(shift_id);

CREATE TABLE refunds (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id    INTEGER NOT NULL REFERENCES orders(id),
  amount      INTEGER NOT NULL,
  method      TEXT NOT NULL,
  reason      TEXT NOT NULL,
  restocked   INTEGER NOT NULL DEFAULT 0,
  approved_by INTEGER NOT NULL REFERENCES users(id),
  user_id     INTEGER NOT NULL REFERENCES users(id),
  shift_id    INTEGER REFERENCES shifts(id),
  created_at  TEXT NOT NULL
);

CREATE TABLE counters (
  name  TEXT PRIMARY KEY,
  value INTEGER NOT NULL
);

CREATE TABLE z_readings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  z_no          INTEGER NOT NULL UNIQUE,
  business_date TEXT NOT NULL UNIQUE,
  data          TEXT NOT NULL,
  user_id       INTEGER NOT NULL REFERENCES users(id),
  created_at    TEXT NOT NULL
);

CREATE TABLE audit_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER REFERENCES users(id),
  action     TEXT NOT NULL,
  entity     TEXT,
  entity_id  INTEGER,
  details    TEXT,
  ip         TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX idx_audit_created ON audit_log(created_at);
